#============================================================================
# Camel Configurations
#============================================================================

camel:
  springboot:
    main-run-controller: true    
  
  component:
    quartz:
      propertiesFile: quartz-cluster.properties                              