#============================================================================
# Camel Configurations
#============================================================================

camel:
  springboot:
    main-run-controller: true    
  
  component:
    quartz:
      properties:
        org.quartz.scheduler.instanceId: AUTO
        org.quartz.scheduler.instanceName: quartzScheduler
        org.quartz.scheduler.skipUpdateCheck: true            
        org.quartz.dataSource.quartzDS.URL: jdbc:postgresql://localhost:5432/quartz_schedule?user=postgres&password=dbpassword
        org.quartz.dataSource.quartzDS.driver: org.postgresql.Driver              
        org.quartz.jobStore.dataSource: quartzDS
        org.quartz.jobStore.class: org.quartz.impl.jdbcjobstore.JobStoreTX 
        org.quartz.jobStore.driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
        org.quartz.jobStore.useProperties: false 
        org.quartz.jobStore.tablePrefix: qrtz_
        org.quartz.jobStore.misfireThreshold: 60000
        org.quartz.jobStore.clusterCheckinInterval: 5000
        org.quartz.jobStore.isClustered: true 
        org.quartz.threadPool.class: org.quartz.simpl.SimpleThreadPool
        org.quartz.threadPool.threadCount: 10
        org.quartz.threadPool.threadPriority: 5                        